markdown: redcarpet
pygments: false
permalink: date
exclude:
  - README.md
redcarpet:
  extensions:
    - fenced_code_blocks
    - autolink
    - tables
    - no_intra_emphasis
    - with_toc_data
    - xhtml
